"""empty message

Revision ID: 52d0e24a5ede
Revises: 84ee5a2cef47
Create Date: 2020-12-28 13:15:08.971848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d0e24a5ede'
down_revision = '84ee5a2cef47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))

    op.execute('UPDATE public."Artist" SET seeking_venue = False WHERE seeking_venue IS NULL;')
    op.execute('UPDATE public."Venue" SET seeking_talent = False WHERE seeking_talent IS NULL;')

    op.alter_column('Artist', 'seeking_venue', nullable=False)
    op.alter_column('Venue', 'seeking_talent', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
