"""empty message

Revision ID: d3649959e5ff
Revises: 52d0e24a5ede
Create Date: 2020-12-28 16:33:53.817934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3649959e5ff'
down_revision = '52d0e24a5ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=240), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
